# Generated by Django 3.2.5 on 2021-09-20 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='venue',
            field=models.CharField(default='balls', max_length=100),
            preserve_default=False,
        ),
    ]
